name = "MLJLIBSVMInterface"
uuid = "61c7150f-6c77-4bb1-949c-13197eac2a52"
authors = ["Anthony D. Blaom <anthony.blaom@gmail.com>"]
version = "0.1.2"

[deps]
LIBSVM = "b1bec4e5-fd48-53fe-b0cb-9723c09d164b"
MLJModelInterface = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
MLJModelInterface = "^0.3.6,^0.4"
LIBSVM = "^0.4, 0.5"
julia = "^1"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["LinearAlgebra", "MLJBase", "StableRNGs", "Test"]
